# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - Comms SMS Module

on:
  push:
    branches:
      - main
    paths:
      - 'Partner.Comms.SMS.SquareTrade.FuncApp/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: 'v3.1.301'  # set this to the dotnet version to use
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "Partner.Comms.SMS.SquareTrade.FuncApp/" 
  AZURE_COMMON_PACKAGE_PATH: "Partner.Comms.SquareTrade.Common/"
  AZURE_DTO_PACKAGE_PATH: "Partner.Comms.SquareTrade.DTO/"
  AZURE_DOMAIN_PACKAGE_PATH: "Partner.Comms.SquareTrade.Domain/"
  AZURE_SERVICE_PACKAGE_PATH: "Partner.Comms.SquareTrade.Service/"
  AZURE_TESTS_PACKAGE_PATH: "Partner.Comms.SquareTrade.Tests/"
  AZURE_REPOSITORY_PACKAGE_PATH: "Partner.Comms.SquareTrade.Repository/"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        pushd '../${{ env.AZURE_COMMON_PACKAGE_PATH }}'
        pushd '../${{ env.AZURE_DTO_PACKAGE_PATH }}'
        pushd '../${{ env.AZURE_DOMAIN_PACKAGE_PATH }}'
        pushd '../${{ env.AZURE_SERVICE_PACKAGE_PATH }}'        
        pushd '../${{ env.AZURE_TESTS_PACKAGE_PATH }}'
        pushd '../${{ env.AZURE_REPOSITORY_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'MultiFunctionDeploy-Func1'
        slot-name: 'production'
        package: '${{ env.AZURE_REPOSITORY_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_SMS }}
